name: JoinMessages
main: com.github.winneonsword.JM.MainJM
version: 1.3-b
commands:
  jm:
    description: Host command.
    usage: /jm ?
    permission: joinmessages.jm
    permission-message: You do not have permission to execute this command!
permissions:
  joinmessages.*:
    description: Gives access to all commands within /jm.
    children:
      joinmessages.jm: true
      joinmessages.reload: true
      joinmessages.add: true
      joinmessages.remove: true
  joinmessages.add:
    description: Gives access to all commands regarding adding messages to the config.
    children:
      joinmessages.add.join: true
      joinmessages.add.leave: true
  joinmessages.remove:
    description: Gives access to all commands regarding removing messages to the config.
    children:
      joinmessages.remove.join: true
      joinmessages.remove.leave: true
  joinmessages.jm:
    description: Gives access to the /jm command.
  joinmessages.reload:
    description: Gives access to reload the JM config file.
  joinmessages.add.join:
    description: Gives access to add join messages to the config.
  joinmessages.add.leave:
    description: Gives access to add leave messages to the config.
  joinmessages.remove.join:
    description: Gives access to remove join messsages from the config.
  joinmessages.remove.leave:
    description: Gives access to remove leave messages from the config.